spring.application.name=binance-trading-bot

#Configuracao com a base de dados mysql
spring.datasource.url=jdbc:mysql://ibmec-cloud-trading-bot.mysql.database.azure.com/tradingbot
spring.datasource.username=Cvbarro
spring.datasource.password=CvVtJp123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true